import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./componants/Nav";
import Footer from "./componants/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Perfect Scape",
  description: "Generated by ahmedSayed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
        </body>
    </html>
  );
}
